[default]
extend-ignore-re = [
    "0x[0-9a-fA-F]+", # Hexadecimal numbers
]

[default.extend-words]
groth16 = "groth16"
groth = "groth"

[files]
ignore-hidden = true
extend-exclude = [
    "circuits/src/circomlib/",
]