# https://embarkstudios.github.io/cargo-deny/index.html

[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "aarch64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "aarch64-apple-darwin" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
    { triple = "wasm32-unknown-unknown" },
    { triple = "wasm32-wasi" },
    { triple = "aarch64-linux-android" },
    { triple = "aarch64-apple-ios" },
]
all-features = true
no-default-features = false

[output]
feature-depth = 1

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "deny"
ignore = []
unmaintained = "workspace"

[licenses]
allow = [
    "0BSD",
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "CC-BY-1.0",
    "CC-BY-2.0",
    "CC-BY-3.0",
    "CC-BY-4.0",
    "CC0-1.0",
    "ISC",
    "OpenSSL",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "Zlib",
]
confidence-threshold = 0.8
unused-allowed-license = "allow"
exceptions = [
    { allow = ["GPL-3.0"], name = "compiler" },
    { allow = ["GPL-3.0"], name = "constraint_generation" },
    { allow = ["GPL-3.0"], name = "constraint_writers" },
    { allow = ["GPL-3.0"], name = "parser" },
    { allow = ["GPL-3.0"], name = "program_structure" },
    { allow = ["GPL-3.0"], name = "type_analysis" },
    { allow = ["GPL-3.0"], name = "dag" },
    { allow = ["GPL-3.0"], name = "code_producers" },
    { allow = ["GPL-3.0"], name = "circom_algebra" },
    { allow = ["GPL-3.0"], name = "constraint_list" },
    { allow = ["GPL-3.0"], name = "constant_tracking" },
]

[licenses.private]
ignore = false
registries = []

[[licenses.clarify]]
name = "compiler"
version = "2.2.2"
expression = "GPL-3.0"
license-files = []

[[licenses.clarify]]
name = "constraint_generation"
version = "2.2.2"
expression = "GPL-3.0"
license-files = []

[[licenses.clarify]]
name = "constraint_writers"
version = "2.2.2"
expression = "GPL-3.0"
license-files = []

[[licenses.clarify]]
name = "parser"
version = "2.2.2"
expression = "GPL-3.0"
license-files = []

[[licenses.clarify]]
name = "program_structure"
version = "2.2.2"
expression = "GPL-3.0"
license-files = []

[[licenses.clarify]]
name = "type_analysis"
version = "2.2.2"
expression = "GPL-3.0"
license-files = []

[[licenses.clarify]]
name = "dag"
version = "2.2.0"
expression = "GPL-3.0"
license-files = []

[[licenses.clarify]]
name = "code_producers"
version = "2.2.2"
expression = "GPL-3.0"
license-files = []

[[licenses.clarify]]
name = "circom_algebra"
version = "2.2.2"
expression = "GPL-3.0"
license-files = []

[[licenses.clarify]]
name = "constraint_list"
version = "2.1.8"
expression = "GPL-3.0"
license-files = []

[[licenses.clarify]]
name = "constant_tracking"
version = "2.0.0"
expression = "GPL-3.0"
license-files = []

[bans]
wildcards = "deny"
allow-wildcard-paths = true
multiple-versions = "warn"
highlight = "all"

[bans.workspace-dependencies]
duplicates = 'deny'
# TODO(template) you should provide an example with the lib usage
unused = 'deny'

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = ["https://github.com/iden3/circom"]

[sources.allow-org]
github = ["NethermindEth"]
gitlab = []
bitbucket = []