name: Contracts Build

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-contracts:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@a54b7f31ebfbf58913f6bf8bb5d8523a23a41a63 # stable
        with:
          toolchain: stable

      - name: Install System dependencies
        run: sudo apt-get update && sudo apt-get install -y libdbus-1-dev libudev-dev pkg-config

      - name: Install wasm target
        run: rustup target add wasm32v1-none

      - uses: Swatinem/rust-cache@82a92a6e8fbeee089604da2575dc567ae9ddeaab # v2

      - name: Install Stellar CLI
        uses: stellar/stellar-cli@bc48e47c1a51c58a498126a93e00dea1a74f9a81 # v25.1.0

      - name: Build contracts
        run: |
          mkdir -p target/stellar
          for pkg in asp-membership asp-non-membership circom-groth16-verifier pool; do
            stellar contract build --manifest-path Cargo.toml --out-dir target/stellar --optimize \
              --package "$pkg"
          done
