name: Docs

on:
  workflow_dispatch:

jobs:
  docs:
    permissions:
      contents: write
      pages: write
      id-token: write
    name: Documentation
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Setup pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Install mdBook
        run: cargo install mdbook --no-default-features

      - name: Resolve symlinks in docs
        run: |
          cd docs/src
          for f in *.md; do
            if [ -L "$f" ]; then
              cp --remove-destination "$(readlink -f "$f")" "$f"
            fi
          done

      - name: Build mdBook
        env:
          MDBOOK_OUTPUT__HTML__SITE_URL: ${{ steps.pages.outputs.base_url }}/
        run: mdbook build docs/

      - name: Clean docs folder
        run: cargo clean --doc

      - name: Build API documentation
        run: cargo doc --no-deps --workspace

      - name: Combine outputs
        run: |
          rm -f target/doc/.lock
          cp -r target/doc docs/book/api

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/book

  publish-docs:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: docs
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
